SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[GET_PRIC_U](@ExtpCode BIGINT, @BTRFCode BIGINT, @TRFDCode BIGINT) RETURNS BIGINT
AS
BEGIN
   DECLARE @Pric INT;
   SELECT @Pric = PRIC
     FROM Expense 
    WHERE EXTP_CODE = @ExtpCode
      AND BTRF_CODE = @BTRFCode
      AND TRFD_CODE = @TRFDCode;
   RETURN @Pric;   
END
GO
