SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date, ,>
-- Description:	<Description, ,>
-- =============================================
CREATE FUNCTION [dbo].[GET_ITMV_F]
(
	@X XML
)
RETURNS NVARCHAR(4000)
AS
BEGIN
	DECLARE @Fileno BIGINT
	       ,@CompCode BIGINT
	       ,@UserName VARCHAR(250)
	       ,@TempItem VARCHAR(100);
   
  	SELECT @FileNo = @X.query('TemplateItemToText').value('(TemplateItemToText/@fileno)[1]', 'BIGINT')
	      ,@TempItem = @X.query('TemplateItemToText').value('(TemplateItemToText/@tempitem)[1]', 'VARCHAR(100)');
	
	SELECT @CompCode = COMP_CODE_DNRM
	      ,@UserName = UPPER(SUSER_NAME())
	  FROM dbo.Service
	 WHERE FILE_NO = @Fileno;
	
	RETURN 
	   CASE @TempItem
	      -- اطلاعات مشتری
	      WHEN '{SERV_BRTH_DATE_DNRM}' THEN (SELECT dbo.GET_MTOS_U(BRTH_DATE_DNRM) FROM dbo.Service WHERE FILE_NO = @Fileno)
         WHEN '{SERV_BTRF_CODE_DNRM}' THEN (SELECT b.BTRF_DESC FROM dbo.Service s, dbo.Base_Tariff b WHERE s.BTRF_CODE_DNRM = b.CODE AND s.FILE_NO = @Fileno )
         WHEN '{SERV_TRFD_CODE_DNRM}' THEN (SELECT b.TRFD_DESC FROM dbo.Service s, dbo.Base_Tariff_Detail b WHERE s.BTRF_CODE_DNRM = b.BTRF_CODE AND s.TRFD_CODE_DNRM = b.CODE AND s.FILE_NO = @Fileno )
         WHEN '{SERV_CELL_PHON_DNRM}' THEN (SELECT CELL_PHON_DNRM FROM dbo.Service WHERE FILE_NO = @Fileno)
         WHEN '{SERV_TELL_PHON_DNRM}' THEN (SELECT TELL_PHON_DNRM FROM dbo.Service WHERE FILE_NO = @Fileno)
         WHEN '{SERV_COMP_CODE_DNRM}' THEN (SELECT c.NAME FROM dbo.Service s, dbo.Company c WHERE s.COMP_CODE_DNRM = c.CODE AND s.FILE_NO = @Fileno)
         WHEN '{SERV_CONF_DATE}' THEN (SELECT dbo.GET_MTOS_U(CONF_DATE) FROM dbo.Service WHERE FILE_NO = @Fileno)
         WHEN '{SERV_CUST_TYPE_DNRM}' THEN (SELECT d.DOMN_DESC FROM dbo.Service s LEFT OUTER join dbo.[D$CTTP] d ON s.CUST_TYPE_DNRM = d.VALU WHERE FILE_NO = @Fileno)
         WHEN '{SERV_DEBT_DNRM}' THEN (SELECT CAST(DEBT_DNRM AS NVARCHAR(100)) FROM dbo.Service WHERE FILE_NO = @Fileno)
         WHEN '{SERV_EMAL_ADRS_DNRM}' THEN (SELECT EMAL_ADRS_DNRM FROM dbo.Service WHERE FILE_NO = @Fileno)
         WHEN '{SERV_ETHN_CITY_DNRM}' THEN (SELECT d.DOMN_DESC  FROM dbo.Service s LEFT OUTER join dbo.[D$ECTP] d ON s.ETHN_CITY_DNRM = d.VALU WHERE FILE_NO = @Fileno)
         WHEN '{SERV_FACE_BOOK_URL_DNRM}' THEN (SELECT FACE_BOOK_URL_DNRM FROM dbo.Service WHERE FILE_NO = @Fileno)
         WHEN '{SERV_FATH_NAME_DNRM}' THEN (SELECT FATH_NAME_DNRM FROM dbo.Service WHERE FILE_NO = @Fileno)
         WHEN '{SERV_FILE_NO}' THEN CAST(@Fileno AS NVARCHAR(30))
         WHEN '{SERV_FRST_NAME_DNRM}' THEN (SELECT FRST_NAME_DNRM FROM dbo.Service WHERE FILE_NO = @Fileno)
         WHEN '{SERV_ISCP_CODE_DNRM}' THEN (SELECT p.ISCP_DESC  FROM dbo.Service s LEFT OUTER JOIN dbo.Isic_Product p ON s.ISCP_CODE_DNRM = p.CODE AND s.ISCP_ISCA_CODE_DNRM = p.ISCA_CODE AND s.ISCP_ISCA_ISCG_CODE_DNRM = p.ISCA_ISCG_CODE WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_ISCP_ISCA_CODE_DNRM}' THEN (SELECT a.FRSI_DESC  FROM dbo.Service s LEFT OUTER JOIN dbo.Isic_Activity a ON s.ISCP_ISCA_CODE_DNRM = a.CODE AND s.ISCP_ISCA_ISCG_CODE_DNRM = a.ISCG_CODE WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_ISCP_ISCA_ISCG_CODE_DNRM}' THEN (SELECT g.FRSI_DESC  FROM dbo.Service s LEFT OUTER JOIN dbo.Isic_Group g ON s.ISCP_ISCA_ISCG_CODE_DNRM = g.CODE WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_JOB_TITL_DNRM}' THEN (SELECT d.DOMN_DESC FROM dbo.Service s LEFT OUTER JOIN dbo.[D$JBTP] d ON s.JOB_TITL_DNRM = d.VALU WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_LAST_NAME_DNRM}' THEN (SELECT LAST_NAME_DNRM FROM dbo.Service WHERE FILE_NO = @Fileno)
         WHEN '{SERV_LAST_RQST_RQID_DNRM}' THEN (SELECT rt.RQTP_DESC FROM dbo.Service s, dbo.Request r, dbo.Request_Type rt WHERE s.LAST_RQST_RQID_DNRM = r.RQID AND r.RQTP_CODE = rt.CODE AND s.FILE_NO = @Fileno)
         WHEN '{SERV_LINK_IN_URL_DNRM}' THEN (SELECT s.LINK_IN_URL_DNRM FROM dbo.Service s WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_MRID_TYPE_DNRM}' THEN (SELECT d.DOMN_DESC FROM dbo.Service s LEFT OUTER JOIN dbo.[D$MRTP] d ON s.MRID_TYPE_DNRM = d.VALU WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_NAME_DNRM}' THEN (SELECT s.NAME_DNRM FROM dbo.Service s WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_NATL_CODE_DNRM}' THEN (SELECT s.NATL_CODE_DNRM FROM dbo.Service s WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_ONOF_TAG_DNRM}' THEN (SELECT d.DOMN_DESC FROM dbo.Service s LEFT OUTER JOIN dbo.[D$ACTG] d ON s.ONOF_TAG_DNRM = d.VALU WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_POST_ADRS_DNRM}' THEN (SELECT s.POST_ADRS_DNRM FROM dbo.Service s WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_REGN_CODE}' THEN (SELECT r.NAME FROM dbo.Region r, dbo.Service s WHERE s.REGN_CODE = r.CODE AND s.REGN_PRVN_CODE = r.PRVN_CODE AND s.REGN_PRVN_CNTY_CODE = r.PRVN_CNTY_CODE AND s.FILE_NO = @Fileno)
         WHEN '{SERV_REGN_PRVN_CNTY_CODE}' THEN (SELECT c.NAME FROM dbo.Country c, dbo.Service s WHERE s.REGN_PRVN_CNTY_CODE = c.CODE AND s.FILE_NO = @Fileno)
         WHEN '{SERV_REGN_PRVN_CODE}' THEN (SELECT p.NAME FROM dbo.Province p, dbo.Service s WHERE s.REGN_PRVN_CODE = p.CODE AND s.REGN_PRVN_CNTY_CODE = p.CNTY_CODE AND s.FILE_NO = @Fileno)
         WHEN '{SERV_RLGN_TYPE_DNRM}' THEN (SELECT d.DOMN_DESC FROM dbo.Service s LEFT OUTER JOIN dbo.[D$RLTP] d ON s.RLGN_TYPE_DNRM = d.VALU WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_RQST_RQID}' THEN (SELECT rt.RQTP_DESC FROM dbo.Service s, dbo.Request r, dbo.Request_Type rt WHERE s.RQST_RQID = r.RQID AND r.RQTP_CODE = rt.CODE AND s.FILE_NO = @Fileno)
         WHEN '{SERV_SCOR_LEVL_DNRM}' THEN (SELECT CAST(s.SCOR_LEVL_DNRM AS NVARCHAR(100)) FROM dbo.Service s WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_SEX_TYPE_DNRM}' THEN (SELECT d.DOMN_DESC FROM dbo.Service s LEFT OUTER JOIN dbo.[D$SXDC] d ON s.SEX_TYPE_DNRM = d.VALU WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_SRPB_TYPE_DNRM}' THEN (SELECT d.DOMN_DESC FROM dbo.Service s LEFT OUTER JOIN dbo.[D$SRTP] d ON s.SRPB_TYPE_DNRM = d.VALU WHERE s.FILE_NO = @Fileno)
         WHEN '{SERV_SUNT_CODE_DNRM}' THEN (SELECT b.SUNT_DESC FROM dbo.Service s LEFT OUTER JOIN dbo.Sub_Unit b ON s.SUNT_CODE_DNRM = b.CODE AND s.SUNT_BUNT_CODE_DNRM = b.BUNT_CODE AND s.SUNT_BUNT_DEPT_CODE_DNRM = b.BUNT_DEPT_CODE AND s.SUNT_BUNT_DEPT_ORGN_CODE_DNRM = b.BUNT_DEPT_ORGN_CODE  WHERE s.FILE_NO = @Fileno )
         WHEN '{SERV_SUNT_BUNT_CODE_DNRM}' THEN (SELECT b.BUNT_DESC FROM dbo.Service s LEFT OUTER JOIN dbo.Base_Unit b  ON s.SUNT_BUNT_CODE_DNRM = b.CODE AND s.SUNT_BUNT_DEPT_CODE_DNRM = b.DEPT_CODE AND s.SUNT_BUNT_DEPT_ORGN_CODE_DNRM = b.DEPT_ORGN_CODE WHERE s.FILE_NO = @Fileno )
         WHEN '{SERV_SUNT_BUNT_DEPT_CODE_DNRM}' THEN (SELECT b.DEPT_DESC FROM dbo.Service s LEFT OUTER JOIN dbo.Department b ON s.SUNT_BUNT_DEPT_CODE_DNRM = b.CODE AND s.SUNT_BUNT_DEPT_ORGN_CODE_DNRM = b.ORGN_CODE WHERE s.FILE_NO = @Fileno )
         WHEN '{SERV_SUNT_BUNT_DEPT_ORGN_CODE_DNRM}' THEN (SELECT b.ORGN_DESC FROM dbo.Service s LEFT OUTER JOIN dbo.Organ b ON s.SUNT_BUNT_DEPT_ORGN_CODE_DNRM = b.CODE WHERE s.FILE_NO = @Fileno )         
         WHEN '{SERV_TWTR_URL_DNRM}' THEN (SELECT s.TWTR_URL_DNRM FROM dbo.Service s WHERE s.FILE_NO = @Fileno)
         -- اطلاعات شرکت
         WHEN '{COMP_COMP_DESC}' THEN (SELECT ISNULL(COMP_DESC, '*') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_DEBT_DNRM}' THEN (SELECT ISNULL(CAST(DEBT_DNRM AS NVARCHAR(100)), '0') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_ECON_CODE}' THEN (SELECT ISNULL(ECON_CODE, '*') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_EMAL_ADRS}' THEN (SELECT ISNULL(EMAL_ADRS, '*') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_EMPY_NUMB_DNRM}' THEN (SELECT ISNULL(CAST(EMPY_NUMB_DNRM AS NVARCHAR(100)), '0') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_END_TIME}' THEN (SELECT ISNULL(CAST(CAST(END_TIME AS TIME(0)) AS NVARCHAR(5)), '*') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_FACE_BOOK_URL}' THEN (SELECT ISNULL(FACE_BOOK_URL, '*') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_LINK_IN_URL}' THEN (SELECT ISNULL(LINK_IN_URL, '*') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_NAME}' THEN (SELECT ISNULL(NAME, '*') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_POST_ADRS}' THEN (SELECT ISNULL(POST_ADRS, '*') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_REGN_CODE}' THEN (SELECT r.NAME FROM dbo.Region r, dbo.Company c WHERE r.CODE = c.REGN_CODE AND r.PRVN_CODE = c.REGN_PRVN_CODE AND r.PRVN_CNTY_CODE = c.REGN_PRVN_CNTY_CODE AND c.CODE = @CompCode)
         WHEN '{COMP_REGN_PRVN_CNTY_CODE}' THEN (SELECT c.NAME FROM dbo.Country c, dbo.Company cm WHERE c.CODE = cm.REGN_PRVN_CNTY_CODE AND cm.CODE = @CompCode)
         WHEN '{COMP_REGN_PRVN_CODE}' THEN (SELECT p.NAME FROM dbo.Province p, dbo.Company c WHERE p.CODE = c.REGN_PRVN_CODE AND p.CNTY_CODE = c.REGN_PRVN_CNTY_CODE AND c.CODE = @CompCode)
         WHEN '{COMP_REGS_DATE}' THEN (SELECT ISNULL(dbo.GET_MTOS_U(REGS_DATE), '0') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_STRT_TIME}' THEN (SELECT ISNULL(CAST(CAST(STRT_TIME AS TIME(0)) AS NVARCHAR(5)), '*') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_TWTR_URL}' THEN (SELECT ISNULL(TWTR_URL, '*') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_WEB_SITE}' THEN (SELECT ISNULL(WEB_SITE, '*') FROM dbo.Company WHERE CODE = @CompCode)
         WHEN '{COMP_ZIP_CODE}' THEN (SELECT ISNULL(ZIP_CODE, '*') FROM dbo.Company WHERE CODE = @CompCode)
         -- اطلاعات کاربر
         WHEN '{USER_CELL_PHON}' THEN (SELECT ISNULL(CELL_PHON, '*') FROM dbo.V#Users WHERE USER_DB = UPPER(SUSER_NAME()))
         WHEN '{USER_EMAL_ADRS}' THEN (SELECT ISNULL(EMAL_ADRS, '*') FROM dbo.V#Users WHERE USER_DB = UPPER(SUSER_NAME()))
         WHEN '{USER_TELL_PHON}' THEN (SELECT ISNULL(TELL_PHON, '*') FROM dbo.V#Users WHERE USER_DB = UPPER(SUSER_NAME()))
         WHEN '{USER_USER_DB}' THEN (SELECT ISNULL(USER_DB, '*') FROM dbo.V#Users WHERE USER_DB = UPPER(SUSER_NAME()))
         WHEN '{USER_USER_NAME}' THEN (SELECT ISNULL([USER_NAME], '*') FROM dbo.V#Users WHERE USER_DB = UPPER(SUSER_NAME()))
         WHEN '{USER_VOIP_NUMB}' THEN (SELECT ISNULL(VOIP_NUMB, '*') FROM dbo.V#Users WHERE USER_DB = UPPER(SUSER_NAME()))
	   END;
END
GO
