SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VF$Access_Profiler]
AS
SELECT     USER_NAME, ROLE_ID, ROLE_NAME, PROF_NAME, PROF_ID, DSRC_ID, SUB_SYS
FROM         iProject.Report.v$AccessProfilers
WHERE     (UPPER(USER_NAME) = UPPER(SUSER_NAME()))
GO
